const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  DIETICIAN: 'DIETICIAN',
  KITCHEN_STAFF: 'KITCHEN_STAFF',
  DELIVERY_STAFF: 'DELIVERY_STAFF',
  PATIENT: 'PATIENT'
});

const ROLE_VALUES = Object.freeze(Object.values(ROLES));

const DIET_TYPES = Object.freeze([
  'DIABETIC',
  'LOW_SODIUM',
  'LIQUID',
  'HIGH_PROTEIN',
  'NORMAL'
]);

const RESTRICTIONS = Object.freeze([
  'GLUTEN_FREE',
  'NUT_ALLERGY',
  'LACTOSE_INTOLERANCE',
  'VEGETARIAN',
  'JAIN'
]);

const MEAL_TYPES = Object.freeze([
  'BREAKFAST',
  'LUNCH',
  'EVENING_SNACKS',
  'DINNER'
]);

const MEAL_STATUSES = Object.freeze([
  'SCHEDULED',
  'PREPARED',
  'PACKED',
  'DISPATCHED',
  'DELIVERED',
  'CANCELLED'
]);

const MENU_ITEM_TYPES = Object.freeze([
  'NORMAL_SET',
  'JUMBO_SET',
  'INDIVIDUAL_ITEM',
  'CUSTOMIZABLE'
]);

const FOOD_ORDER_STATUSES = Object.freeze([
  'PLACED',
  'ACCEPTED',
  'PREPARING',
  'READY_FOR_PICKUP',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'CANCELLED'
]);

const PAYMENT_METHODS = Object.freeze(['CASH', 'ONLINE']);

const QUERY_STATUSES = Object.freeze(['OPEN', 'ANSWERED', 'CLOSED']);

const PRESCRIPTION_STATUSES = Object.freeze([
  'PENDING',
  'APPROVED',
  'REJECTED',
  'SUPERSEDED'
]);

const INVENTORY_TXN_TYPES = Object.freeze([
  'PURCHASE',
  'CONSUMPTION',
  'ADJUSTMENT',
  'WASTAGE'
]);

const BILLING_STATUSES = Object.freeze([
  'PENDING',
  'POSTED',
  'PAID',
  'WAIVED'
]);

const NOTIFICATION_TYPES = Object.freeze([
  'DIET_CHANGED',
  'LOW_STOCK',
  'PENDING_DELIVERY',
  'GENERAL'
]);

const NOTIFICATION_CHANNELS = Object.freeze([
  'IN_APP',
  'EMAIL',
  'SMS'
]);

const DIET_COST = Object.freeze({
  DIABETIC: 160,
  LOW_SODIUM: 145,
  LIQUID: 120,
  HIGH_PROTEIN: 180,
  NORMAL: 100
});

module.exports = {
  ROLES,
  ROLE_VALUES,
  DIET_TYPES,
  RESTRICTIONS,
  MEAL_TYPES,
  MEAL_STATUSES,
  MENU_ITEM_TYPES,
  FOOD_ORDER_STATUSES,
  PAYMENT_METHODS,
  QUERY_STATUSES,
  PRESCRIPTION_STATUSES,
  INVENTORY_TXN_TYPES,
  BILLING_STATUSES,
  NOTIFICATION_TYPES,
  NOTIFICATION_CHANNELS,
  DIET_COST
};
